"""create RouteAI schema

Revision ID: 94ed2c1913f7
Revises: 
Create Date: 2026-07-23 16:17:39.550895
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '94ed2c1913f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('responsibility', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_ai_agents_agent_name'), 'ai_agents', ['agent_name'], unique=True)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('document_embeddings',
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_vector_id'), 'document_embeddings', ['vector_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('action_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_time'), 'audit_logs', ['action_time'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='available', nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Float(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('optimized', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_driver_id'), 'routes', ['driver_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='available', nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(length=500), nullable=False),
    sa.Column('drop_location', sa.String(length=500), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=50), server_default='normal', nullable=False),
    sa.Column('delivery_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_deliveries_customer_id'), 'deliveries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deliveries_delivery_status'), 'deliveries', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_deliveries_driver_id'), 'deliveries', ['driver_id'], unique=False)
    op.create_index('ix_deliveries_status_created_at', 'deliveries', ['delivery_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_deliveries_vehicle_id'), 'deliveries', ['vehicle_id'], unique=False)
    op.create_table('route_adjustments',
    sa.Column('adjustment_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('updated_route', sa.Text(), nullable=False),
    sa.Column('adjusted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_index(op.f('ix_route_adjustments_route_id'), 'route_adjustments', ['route_id'], unique=False)
    op.create_table('route_optimizations',
    sa.Column('optimization_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('fuel_saved', sa.Float(), nullable=False),
    sa.Column('distance_saved', sa.Float(), nullable=False),
    sa.Column('time_saved', sa.Float(), nullable=False),
    sa.Column('optimized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('optimization_id')
    )
    op.create_index(op.f('ix_route_optimizations_route_id'), 'route_optimizations', ['route_id'], unique=False)
    op.create_table('traffic_data',
    sa.Column('traffic_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('traffic_level', sa.String(length=50), nullable=False),
    sa.Column('incident', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('traffic_id')
    )
    op.create_index(op.f('ix_traffic_data_route_id'), 'traffic_data', ['route_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('task_result', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.agent_id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_agent_tasks_agent_id'), 'agent_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_delivery_id'), 'agent_tasks', ['delivery_id'], unique=False)
    op.create_table('delivery_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schedule_status', sa.String(length=50), server_default='scheduled', nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_delivery_schedules_delivery_id'), 'delivery_schedules', ['delivery_id'], unique=False)
    op.create_table('driver_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assignment_status', sa.String(length=50), server_default='assigned', nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_driver_assignments_assignment_status'), 'driver_assignments', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_driver_assignments_delivery_id'), 'driver_assignments', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_table('eta_predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('predicted_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_eta_predictions_delivery_id'), 'eta_predictions', ['delivery_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.delivery_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('stop_id'),
    sa.UniqueConstraint('route_id', 'delivery_id', name='uq_route_stops_route_delivery'),
    sa.UniqueConstraint('route_id', 'stop_sequence', name='uq_route_stops_route_sequence')
    )
    op.create_index(op.f('ix_route_stops_delivery_id'), 'route_stops', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_delivery_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_eta_predictions_delivery_id'), table_name='eta_predictions')
    op.drop_table('eta_predictions')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_delivery_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_assignment_status'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_delivery_schedules_delivery_id'), table_name='delivery_schedules')
    op.drop_table('delivery_schedules')
    op.drop_index(op.f('ix_agent_tasks_delivery_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_traffic_data_route_id'), table_name='traffic_data')
    op.drop_table('traffic_data')
    op.drop_index(op.f('ix_route_optimizations_route_id'), table_name='route_optimizations')
    op.drop_table('route_optimizations')
    op.drop_index(op.f('ix_route_adjustments_route_id'), table_name='route_adjustments')
    op.drop_table('route_adjustments')
    op.drop_index(op.f('ix_deliveries_vehicle_id'), table_name='deliveries')
    op.drop_index('ix_deliveries_status_created_at', table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_driver_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivery_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_customer_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_routes_driver_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_time'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_document_embeddings_vector_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_ai_agents_agent_name'), table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
